service: "${file(../config.json):service}-interface"

provider:
    name: aws
    runtime: nodejs14.x

plugins:
    - serverless-s3-sync

custom:
    bucketName: "${file(../config.json):service}-deployment-bucket"
    s3Sync:
        noSync: true
        buckets:
        - bucketName: ${self:custom.bucketName}
          localDir: build/

resources:
    Resources:
        ReactAppBucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${self:custom.bucketName}
                WebsiteConfiguration:
                    IndexDocument: index.html
                    ErrorDocument: index.html
        S3AccessPolicy:
            Type: AWS::S3::BucketPolicy
            Properties:
                Bucket:
                    Ref: ReactAppBucket
                PolicyDocument:
                    Statement:
                        - Sid: PublicReadGetObject
                          Effect: Allow
                          Principal: '*'
                          Resource: arn:aws:s3:::${self:custom.bucketName}/*
        CloudFrontDistribution:
            Type: AWS::CloudFront::Distribution
            Properties:
                DistributionConfig:
                    Origins:
                        - DomainName: ${self:custom.bucketName}.s3.amazonaws.com
                          Id: ReactApp
                          CustomOriginConfig:
                              HTTPPort: 80
                              HTTPSPort: 443
                              OriginProtocolPolicy: https-only
                    Enabled: true
                    DefaultRootObject: index.html
                    CustomErrorResponses:
                        - ErrorCode: 404
                          ResponseCode: 200
                          ResponsePagePath: /index.html
                    DefaultCacheBehavior:
                        AllowedMethods:
                            - HEAD
                            - GET
                        TargetOriginId: ReactApp
                        ForwardedValues:
                            QueryString: false
                            Cookies:
                                Forward: none
                        ViewerProtocolPolicy: redirect-to-https
                    ViewerCertificate:
                        CloudFrontDefaultCertificate: true
